[package]
name = "satusd-lock"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bitcoin = "0.32.9"
satusd-crypto = { path = "../satusd-crypto" }
satusd-types = { path = "../satusd-types" }

[dev-dependencies]
hex.workspace = true
