[package]
name = "satusd-challenger"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
satusd-types = { path = "../satusd-types" }
satusd-da = { path = "../satusd-da" }
satusd-ta-proof = { path = "../satusd-ta-proof" }
satusd-state = { path = "../satusd-state" }

[dev-dependencies]
hex.workspace = true
