[Application Options]
debuglevel=info
maxpendingchannels=10
accept-keysend=true
listen=127.0.0.1:9736
rpclisten=127.0.0.1:10010
restlisten=127.0.0.1:8081

[Bitcoin]
bitcoin.active=true
bitcoin.signet=true
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=127.0.0.1:38332
bitcoind.rpcuser=satusd
bitcoind.rpcpass=satusd
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28342
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28343
