[package]
name = "satusd-rail1"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
satusd-oracle = { path = "../satusd-oracle" }
satusd-rail = { path = "../satusd-rail" }
secp256k1 = "0.31.1"

[dev-dependencies]
hex.workspace = true
